"""Add payment_method and customer_name to TransactionGroup

Revision ID: 4d990fdda7e7
Revises: a66cb8456c56
Create Date: 2025-09-02 05:29:47.977702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d990fdda7e7'
down_revision = 'a66cb8456c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_group', schema=None) as batch_op:
        batch_op.drop_column('customer_name')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
